@extends('admin.layout.app')

@section('title', __('admin.orders_management'))

@section('content')
@php
    $money = static fn ($amount) => number_format((float) $amount, 2) . ' ل.س';
@endphp
<div class="page-header"><div><p class="eyebrow">{{ __('admin.store') }}</p><h1>{{ __('admin.orders_management') }}</h1><p>{{ __('admin.orders_management_hint') }}</p></div></div>
<form method="GET" class="panel-card form-panel mb-4" role="search"><div class="row g-3 align-items-end"><div class="col-lg-5"><label class="form-label" for="order-search">{{ __('admin.search_orders') }}</label><div class="input-group"><span class="input-group-text"><i class="fas fa-search"></i></span><input id="order-search" type="search" name="search" class="form-control" value="{{ $filters['search'] ?? '' }}" placeholder="{{ __('admin.search_orders_hint') }}"></div></div><div class="col-sm-6 col-lg-3"><label class="form-label" for="order-status">{{ __('admin.status') }}</label><select id="order-status" name="status" class="form-select"><option value="">{{ __('admin.all_statuses') }}</option>@foreach(['pending','accepted','ready','paid','shipped','delivered','cancelled'] as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ __('admin.status_' . $status) }}</option>@endforeach</select></div><div class="col-sm-6 col-lg-2"><label class="form-label" for="delivery-filter">{{ __('admin.delivery') }}</label><select id="delivery-filter" name="delivery_method" class="form-select"><option value="">{{ __('admin.all_methods') }}</option>@foreach(['clinic_pickup','pharmacy_pickup','home_delivery','qadmous'] as $method)<option value="{{ $method }}" @selected(($filters['delivery_method'] ?? '') === $method)>{{ __('admin.' . $method) }}</option>@endforeach</select></div><div class="col-lg-2"><div class="d-flex gap-2"><button class="btn btn-primary flex-grow-1">{{ __('admin.filter') }}</button>@if(array_filter($filters ?? []))<a href="{{ route('admin.orders.index') }}" class="btn btn-outline-secondary" title="{{ __('admin.clear_filters') }}"><i class="fas fa-rotate-left"></i></a>@endif</div></div></div></form>
<section class="panel-card data-panel"><div class="panel-heading"><div><h3>{{ __('admin.orders') }}</h3><p>{{ __('admin.orders_table_hint') }}</p></div><span class="soft-count">{{ $orders->total() }}</span></div><div class="table-responsive"><table class="table align-middle mb-0 admin-data-table"><thead><tr><th>{{ __('admin.order_id') }}</th><th>{{ __('admin.date') }}</th><th>{{ __('admin.customer') }}</th><th>{{ __('admin.total') }}</th><th>{{ __('admin.payment') }}</th><th>{{ __('admin.delivery') }}</th><th>{{ __('admin.status') }}</th><th class="text-end">{{ __('admin.action') }}</th></tr></thead><tbody>
    @forelse($orders as $order)
        @php
            $statusKey = 'admin.status_' . $order->status;
            $paymentKey = match ($order->payment_method) { 'cash_on_delivery' => 'admin.cash_on_delivery', 'credit_card' => 'admin.credit_card', 'online', 'apple_pay' => 'admin.online_payment', default => 'admin.cash' };
            $deliveryKey = 'admin.' . ($order->delivery_method ?: 'home_delivery');
        @endphp
        <tr class="clickable-row" data-href="{{ route('admin.orders.show', $order->id) }}"><td class="fw-bold">#{{ $order->id }}</td><td class="text-muted">{{ $order->created_at->locale(app()->getLocale())->translatedFormat('d M Y، H:i') }}</td><td><strong>{{ $order->user?->name ?? __('admin.unknown_customer') }}</strong><small class="d-block text-muted" dir="ltr">{{ $order->user?->phone }}</small></td><td class="fw-bold">{{ $money($order->total_amount) }}@if(($order->discount_amount ?? 0) > 0)<small class="d-block text-success">-{{ $money($order->discount_amount) }} {{ __('admin.discount') }}</small>@endif</td><td><span class="status-pill info">{{ __($paymentKey) }}</span><small class="d-block text-muted">{{ $order->payment_status === 'paid' ? __('admin.paid') : __('admin.unpaid') }}</small></td><td><span>{{ trans()->has($deliveryKey) ? __($deliveryKey) : ucfirst(str_replace('_', ' ', $order->delivery_method)) }}</span>@if($order->deliveryArea)<small class="d-block text-muted">{{ app()->getLocale() === 'ar' ? $order->deliveryArea->name_ar : $order->deliveryArea->name_en }}</small>@elseif($order->pickup_location)<small class="d-block text-muted">{{ __('admin.' . $order->pickup_location) }}</small>@else<small class="d-block text-muted">{{ __('admin.no_area') }}</small>@endif</td><td><span class="status-pill {{ in_array($order->status, ['cancelled', 'canceled']) ? 'danger' : (in_array($order->status, ['delivered', 'paid']) ? 'success' : 'warning') }}">{{ trans()->has($statusKey) ? __($statusKey) : ucfirst($order->status) }}</span></td><td><div class="action-toolbar justify-content-end">@if(auth()->user()->hasRole('delivery')) @if($order->status !== 'delivered')<form action="{{ route('admin.orders.updateStatus', $order->id) }}" method="POST">@csrf @method('PUT')<input type="hidden" name="status" value="delivered"><button type="submit" class="btn btn-sm btn-success">{{ __('admin.mark_delivered') }}</button></form>@endif @else<form action="{{ route('admin.orders.updateStatus', $order->id) }}" method="POST">@csrf @method('PUT')<select name="status" class="form-select form-select-sm" onchange="this.form.submit()">@foreach(['pending', 'accepted', 'ready', 'paid', 'shipped', 'delivered', 'cancelled'] as $status)<option value="{{ $status }}" @selected($order->status === $status)>{{ __('admin.status_' . $status) }}</option>@endforeach</select></form>@endif<a href="{{ route('admin.orders.show', $order->id) }}" class="btn btn-sm btn-light" title="{{ __('admin.view_details') }}"><i class="fas fa-eye"></i></a></div></td></tr>
    @empty
        <tr><td colspan="8" class="empty-table"><i class="fas fa-shopping-cart"></i><span>{{ __('admin.no_orders_found') }}</span></td></tr>
    @endforelse
    </tbody></table></div>@if($orders->hasPages())<div class="pt-3">{{ $orders->links('pagination::bootstrap-5') }}</div>@endif</section>
@endsection
