@extends('admin.layout.app')

@section('title', __('admin.order_details') . ' #' . $order->id)

@section('content')
@php
    $money = static fn ($amount) => number_format((float) $amount, 2) . ' ل.س';
    $usd = static fn ($amount) => $amount !== null ? '$' . number_format((float) $amount, 2) : null;
    $statusKey = 'admin.status_' . $order->status;
    $paymentKey = match ($order->payment_method) { 'cash_on_delivery' => 'admin.cash_on_delivery', 'credit_card' => 'admin.credit_card', 'online', 'apple_pay' => 'admin.online_payment', default => 'admin.cash' };
    $deliveryKey = 'admin.' . ($order->delivery_method ?: 'home_delivery');
    $requiresReceipt = !in_array($order->payment_method, ['cash', 'cash_on_delivery'], true);
    $itemsSubtotal = $order->items->sum(fn ($item) => $item->price * $item->quantity);
@endphp
<div class="page-header"><div><p class="eyebrow">{{ __('admin.orders') }} · #{{ $order->id }}</p><h1>{{ __('admin.order_details') }}</h1><p>{{ $order->created_at->locale(app()->getLocale())->translatedFormat('d M Y، H:i') }}</p></div><a href="{{ route('admin.orders.index') }}" class="btn btn-outline-secondary"><i class="fas fa-arrow-{{ app()->getLocale() === 'ar' ? 'right' : 'left' }} me-1"></i>{{ __('admin.back_to_list') }}</a></div>
<div class="row g-4">
    <div class="col-xl-8">
        <section class="panel-card data-panel mb-4"><div class="panel-heading"><div><h3>{{ __('admin.order_items') }}</h3><p>{{ __('admin.order_items_hint') }}</p></div><span class="soft-count">{{ $order->items->sum('quantity') }} {{ __('admin.items') }}</span></div><div class="order-item-list">
            @foreach($order->items as $item)
                <div class="order-item-card"><div class="order-item-image">@if($item->product?->image)<img src="{{ asset('storage/' . $item->product->image) }}" alt="">@else<i class="fas fa-pump-soap"></i>@endif</div><div class="order-item-copy"><strong>{{ app()->getLocale() === 'ar' ? ($item->product?->name_ar ?: $item->product?->name_en) : ($item->product?->name_en ?: $item->product?->name_ar) }}</strong><small>{{ __('admin.quantity') }}: {{ $item->quantity }}</small></div><div class="order-item-price"><span>{{ $money($item->price) }}@if($item->price_usd !== null) · {{ $usd($item->price_usd) }}@endif</span><small>{{ __('admin.subtotal') }}: {{ $money($item->price * $item->quantity) }}@if($item->price_usd !== null) · {{ $usd($item->price_usd * $item->quantity) }}@endif</small></div></div>
            @endforeach
        </div><div class="totals-box"><div><span>{{ __('admin.subtotal') }}</span><strong>{{ $money($itemsSubtotal) }}</strong></div>@if(($order->discount_amount ?? 0) > 0)<div class="text-success"><span>{{ __('admin.discount') }}</span><strong>-{{ $money($order->discount_amount) }}</strong></div>@endif@if(($order->delivery_fee ?? 0) > 0)<div><span>{{ __('admin.delivery_fee') }}</span><strong>{{ $money($order->delivery_fee) }}</strong></div>@endif<div class="total-line"><span>{{ __('admin.total_amount') }}</span><strong>{{ $money($order->total_amount) }}</strong></div></div></section>
        <section class="panel-card"><div class="panel-heading"><div><h3>{{ __('admin.customer_information') }}</h3><p>{{ __('admin.customer_information_hint') }}</p></div></div><div class="detail-stat-grid"><div><span>{{ __('admin.customer') }}</span><strong>{{ $order->user?->name ?? __('admin.unknown_customer') }}</strong></div><div><span>{{ __('admin.phone_number') }}</span><strong dir="ltr">{{ $order->user?->phone ?? '-' }}</strong></div><div class="wide"><span>{{ __('admin.shipping_address') }}</span><strong>{{ $order->shipping_address ?: __('admin.no_address') }}</strong></div></div></section>
    </div>
    <div class="col-xl-4">
        <section class="panel-card mb-4"><div class="panel-heading"><div><h3>{{ __('admin.order_status') }}</h3><p>{{ __('admin.status_update_hint') }}</p></div><span class="status-pill {{ in_array($order->status, ['cancelled', 'canceled']) ? 'danger' : (in_array($order->status, ['delivered', 'paid']) ? 'success' : 'warning') }}">{{ trans()->has($statusKey) ? __($statusKey) : ucfirst($order->status) }}</span></div><form action="{{ route('admin.orders.updateStatus', $order->id) }}" method="POST">@csrf @method('PUT')@if(auth()->user()->hasRole('delivery'))<input type="hidden" name="status" value="delivered"><button type="submit" class="btn btn-success w-100" @disabled($order->status === 'delivered')>{{ __('admin.mark_delivered') }}</button>@else<select name="status" class="form-select mb-3">@foreach(['pending', 'accepted', 'ready', 'paid', 'shipped', 'delivered', 'cancelled'] as $status)<option value="{{ $status }}" @selected($order->status === $status)>{{ __('admin.status_' . $status) }}</option>@endforeach</select><button type="submit" class="btn btn-primary w-100">{{ __('admin.update_status') }}</button>@endif</form></section>
        <section class="panel-card mb-4"><div class="panel-heading"><div><h3>{{ __('admin.delivery_and_payment') }}</h3><p>{{ __('admin.delivery_payment_hint') }}</p></div></div><div class="info-list"><div><span>{{ __('admin.delivery_method') }}</span><strong>{{ trans()->has($deliveryKey) ? __($deliveryKey) : ucfirst(str_replace('_', ' ', $order->delivery_method)) }}</strong></div>@if($order->delivery_method === 'qadmous')<div><span>{{ __('admin.qadmous_governorate') }}</span><strong>{{ $order->qadmous_governorate ?: '-' }}</strong></div><div><span>{{ __('admin.qadmous_branch') }}</span><strong>{{ $order->qadmous_branch ?: '-' }}</strong></div><div><span>{{ __('admin.recipient') }}</span><strong>{{ $order->recipient_name ?: '-' }} · {{ $order->recipient_phone ?: '-' }}</strong></div><form method="POST" action="{{ route('admin.orders.updateTracking', $order->id) }}" class="mt-2">@csrf @method('PUT')<label for="tracking_number" class="form-label">{{ __('admin.tracking_number') }}</label><div class="input-group"><input id="tracking_number" name="tracking_number" value="{{ $order->tracking_number }}" class="form-control" placeholder="{{ __('admin.tracking_number') }}" required><button class="btn btn-outline-primary">{{ __('admin.save_tracking') }}</button></div></form>@elseif($order->pickup_location)<div><span>{{ __('admin.pickup_location') }}</span><strong>{{ __('admin.' . $order->pickup_location) }}</strong></div>@endif@if($order->deliveryArea)<div><span>{{ __('admin.delivery_area') }}</span><strong>{{ app()->getLocale() === 'ar' ? $order->deliveryArea->name_ar : $order->deliveryArea->name_en }} · {{ $money($order->delivery_fee ?? 0) }}</strong></div>@endif@if($order->deliveryUser)<div><span>{{ __('admin.assigned_delivery') }}</span><strong>{{ $order->deliveryUser->name }}</strong></div>@endif<div><span>{{ __('admin.payment') }}</span><strong>{{ __($paymentKey) }}</strong></div><div><span>{{ __('admin.payment_status') }}</span><strong>{{ $order->payment_status === 'paid' ? __('admin.paid') : __('admin.unpaid') }}</strong></div>@if($order->coupon)<div><span>{{ __('admin.coupon') }}</span><strong>{{ $order->coupon->code }}</strong></div>@endif</div></section>
        @unless(auth()->user()->hasRole('delivery'))<section class="panel-card">@if($requiresReceipt)<div class="panel-heading"><div><h3>{{ __('admin.receipt') }}</h3><p>{{ __('admin.receipt_hint') }}</p></div></div><form action="{{ route('admin.orders.uploadReceipt', $order->id) }}" method="POST" enctype="multipart/form-data">@csrf<input type="file" name="shipping_receipt" class="form-control mb-2" accept="image/*" required><button type="submit" class="btn btn-outline-primary w-100">{{ __('admin.upload_receipt') }}</button></form>@else<div class="notice-card"><i class="fas fa-receipt"></i><span>{{ __('admin.receipt_not_required') }}</span></div>@endif@if($order->shipping_receipt)<a href="{{ asset('storage/' . $order->shipping_receipt) }}" target="_blank" class="file-row mt-3"><i class="fas fa-image"></i><span>{{ __('admin.view_uploaded_receipt') }}</span><i class="fas fa-external-link-alt"></i></a>@endif</section>@endunless
    </div>
</div>
@endsection
