@extends('admin.layout.app')

@section('title', __('admin.appointment_details') . ' #' . $appointment->id)

@section('content')
@php
    $whatsappPhone = preg_replace('/\D+/', '', (string) ($appointment->patient->phone ?? ''));
    if (str_starts_with($whatsappPhone, '00')) $whatsappPhone = substr($whatsappPhone, 2);
    $typeKey = 'admin.type_' . ($appointment->type ?: 'clinic');
    $statusKey = 'admin.status_' . $appointment->status;
@endphp
<div class="page-header"><div><p class="eyebrow">{{ __('admin.appointments') }} · #{{ $appointment->id }}</p><h1>{{ __('admin.appointment_details') }}</h1><p>{{ $appointment->date }} · {{ $appointment->time }}</p></div><a href="{{ route('admin.appointments.index') }}" class="btn btn-outline-secondary"><i class="fas fa-arrow-{{ app()->getLocale() === 'ar' ? 'right' : 'left' }} me-1"></i>{{ __('admin.back_to_list') }}</a></div>
<div class="row g-4">
    <div class="col-xl-7">
        <section class="panel-card mb-4"><div class="panel-heading"><div><h3>{{ __('admin.schedule_information') }}</h3><p>{{ __('admin.appointment_details_hint') }}</p></div><span class="status-pill {{ $appointment->status === 'completed' ? 'success' : (in_array($appointment->status, ['cancelled', 'canceled']) ? 'danger' : 'warning') }}">{{ trans()->has($statusKey) ? __($statusKey) : ucfirst($appointment->status) }}</span></div><div class="detail-stat-grid"><div><span>{{ __('admin.date') }}</span><strong>{{ $appointment->date }}</strong></div><div><span>{{ __('admin.time') }}</span><strong>{{ $appointment->time }}</strong></div><div><span>{{ __('admin.type') }}</span><strong>{{ trans()->has($typeKey) ? __($typeKey) : ucfirst($appointment->type) }}</strong></div><div><span>{{ __('admin.appointment_type') }}</span><strong>{{ $appointment->appointment_type ? __('admin.type_' . $appointment->appointment_type) : __('admin.none') }}</strong></div><div><span>{{ __('admin.specialty') }}</span><strong>{{ __('admin.specialty_' . ($appointment->specialty ?: 'skin')) }}</strong></div><div><span>{{ __('admin.provider_type') }}</span><strong>{{ __('admin.provider_' . ($appointment->provider_type ?: 'doctor')) }}</strong></div><div><span>{{ __('admin.duration') }}</span><strong>{{ $appointment->duration_minutes ? $appointment->duration_minutes . ' ' . __('admin.minutes') : __('admin.none') }}</strong></div></div></section>

        <section class="panel-card mb-4"><div class="panel-heading"><div><h3>{{ __('admin.edit_appointment') }}</h3><p>{{ __('admin.edit_appointment_hint') }}</p></div></div><form action="{{ route('admin.appointments.update', $appointment->id) }}" method="POST">@csrf @method('PUT')<div class="row g-3">
            <div class="col-md-6"><label class="form-label">{{ __('admin.assigned_doctor') }}</label><select name="doctor_id" class="form-select" required>@foreach($doctors as $doctor)<option value="{{ $doctor->id }}" @selected((int)$appointment->doctor_id === (int)$doctor->id)>{{ $doctor->name }}</option>@endforeach</select></div>
            <div class="col-md-6"><label class="form-label">{{ __('admin.provider_type') }}</label><select name="provider_type" class="form-select"><option value="doctor" @selected($appointment->provider_type === 'doctor')>{{ __('admin.provider_doctor') }}</option><option value="team" @selected($appointment->provider_type === 'team')>{{ __('admin.provider_team') }}</option></select></div>
            <div class="col-md-6"><label class="form-label">{{ __('admin.date') }}</label><input type="date" name="date" value="{{ $appointment->date }}" min="{{ now()->toDateString() }}" class="form-control" required></div>
            <div class="col-md-6"><label class="form-label">{{ __('admin.time') }}</label><input type="time" name="time" value="{{ substr($appointment->time, 0, 5) }}" class="form-control" required></div>
            <div class="col-md-4"><label class="form-label">{{ __('admin.type') }}</label><select name="type" class="form-select"><option value="clinic" @selected($appointment->type === 'clinic')>{{ __('admin.type_clinic') }}</option><option value="online" @selected($appointment->type === 'online')>{{ __('admin.type_online') }}</option></select></div>
            <div class="col-md-4"><label class="form-label">{{ __('admin.appointment_type') }}</label><select name="appointment_type" class="form-select">@foreach(['consultation','treatment','session'] as $value)<option value="{{ $value }}" @selected($appointment->appointment_type === $value)>{{ __('admin.type_'.$value) }}</option>@endforeach</select></div>
            <div class="col-md-4"><label class="form-label">{{ __('admin.specialty') }}</label><select name="specialty" class="form-select">@foreach(['skin','hair','nutrition'] as $value)<option value="{{ $value }}" @selected(($appointment->specialty ?: 'skin') === $value)>{{ __('admin.specialty_'.$value) }}</option>@endforeach</select></div>
            <div class="col-12"><label class="form-label">{{ __('admin.internal_notes') }}</label><textarea name="internal_notes" class="form-control" rows="3">{{ old('internal_notes', $appointment->internal_notes) }}</textarea></div>
            <div class="col-12"><button class="btn btn-primary" type="submit"><i class="fas fa-save me-1"></i>{{ __('admin.save_changes') }}</button></div>
        </div></form></section>

        <section class="panel-card"><div class="panel-heading"><div><h3>{{ __('admin.change_status') }}</h3><p>{{ __('admin.status_update_hint') }}</p></div></div><form action="{{ route('admin.appointments.updateStatus', $appointment->id) }}" method="POST">@csrf @method('PUT')<div class="row g-3 align-items-end"><div class="col-md-5"><label for="appointment_status" class="form-label">{{ __('admin.status') }}</label><select id="appointment_status" name="status" class="form-select">@foreach(['pending', 'confirmed', 'completed', 'cancelled'] as $status)<option value="{{ $status }}" @selected($appointment->status === $status)>{{ __('admin.status_' . $status) }}</option>@endforeach</select></div><div class="col-md-5"><label class="form-label">{{ __('admin.cancellation_reason') }}</label><input name="cancellation_reason" class="form-control" value="{{ old('cancellation_reason', $appointment->cancellation_reason) }}" placeholder="{{ __('admin.required_when_cancelled') }}"></div><div class="col-md-2"><button type="submit" class="btn btn-primary w-100">{{ __('admin.update_status') }}</button></div></div></form></section>
    </div>
    <div class="col-xl-5"><section class="panel-card detail-profile-card h-100"><div class="profile-avatar"><i class="fas fa-user-injured"></i></div><h2>{{ $appointment->patient?->name ?? __('admin.unknown') }}</h2><p class="muted-number" dir="ltr">{{ $appointment->patient?->phone ?? '-' }}</p>@if($whatsappPhone !== '')<a href="https://wa.me/{{ $whatsappPhone }}" target="_blank" rel="noopener noreferrer" class="btn btn-outline-success w-100 mt-3"><i class="fab fa-whatsapp me-1"></i>{{ __('admin.open_whatsapp') }}</a>@endif<div class="mt-3"><a href="{{ route('admin.patients.show', $appointment->patient_id) }}" class="btn btn-light w-100"><i class="fas fa-folder-open me-1"></i>{{ __('admin.view_patient_history') }}</a></div></section></div>
</div>
@endsection
