@extends('admin.layout.app')

@section('title', __('admin.appointment_details') . ' #' . $appointment->id)

@section('content')
@php
    $whatsappPhone = preg_replace('/\D+/', '', (string) ($appointment->patient->phone ?? ''));
    if (str_starts_with($whatsappPhone, '00')) $whatsappPhone = substr($whatsappPhone, 2);
    $typeKey = 'admin.type_' . ($appointment->type ?: 'clinic');
    $statusKey = 'admin.status_' . $appointment->status;
@endphp
<div class="page-header"><div><p class="eyebrow">{{ __('admin.appointments') }} · #{{ $appointment->id }}</p><h1>{{ __('admin.appointment_details') }}</h1><p>{{ $appointment->date }} · {{ $appointment->time }}</p></div><a href="{{ route('admin.appointments.index') }}" class="btn btn-outline-secondary"><i class="fas fa-arrow-{{ app()->getLocale() === 'ar' ? 'right' : 'left' }} me-1"></i>{{ __('admin.back_to_list') }}</a></div>
<div class="row g-4">
    <div class="col-xl-7"><section class="panel-card mb-4"><div class="panel-heading"><div><h3>{{ __('admin.schedule_information') }}</h3><p>{{ __('admin.appointment_details_hint') }}</p></div><span class="status-pill {{ $appointment->status === 'completed' ? 'success' : (in_array($appointment->status, ['cancelled', 'canceled']) ? 'danger' : 'warning') }}">{{ trans()->has($statusKey) ? __($statusKey) : ucfirst($appointment->status) }}</span></div><div class="detail-stat-grid"><div><span>{{ __('admin.date') }}</span><strong>{{ $appointment->date }}</strong></div><div><span>{{ __('admin.time') }}</span><strong>{{ $appointment->time }}</strong></div><div><span>{{ __('admin.type') }}</span><strong>{{ trans()->has($typeKey) ? __($typeKey) : ucfirst($appointment->type) }}</strong></div><div><span>{{ __('admin.appointment_type') }}</span><strong>{{ $appointment->appointment_type ? __('admin.type_' . $appointment->appointment_type) : __('admin.none') }}</strong></div><div><span>{{ __('admin.duration') }}</span><strong>{{ $appointment->duration_minutes ? $appointment->duration_minutes . ' ' . __('admin.minutes') : __('admin.none') }}</strong></div></div></section><section class="panel-card"><div class="panel-heading"><div><h3>{{ __('admin.change_status') }}</h3><p>{{ __('admin.status_update_hint') }}</p></div></div><form action="{{ route('admin.appointments.updateStatus', $appointment->id) }}" method="POST" class="d-flex flex-wrap gap-3 align-items-end">@csrf @method('PUT')<div class="flex-grow-1"><label for="appointment_status" class="form-label">{{ __('admin.status') }}</label><select id="appointment_status" name="status" class="form-select">@foreach(['pending', 'confirmed', 'completed', 'cancelled'] as $status)<option value="{{ $status }}" @selected($appointment->status === $status)>{{ __('admin.status_' . $status) }}</option>@endforeach</select></div><button type="submit" class="btn btn-primary">{{ __('admin.update_status') }}</button></form></section></div>
    <div class="col-xl-5"><section class="panel-card detail-profile-card h-100"><div class="profile-avatar"><i class="fas fa-user-injured"></i></div><h2>{{ $appointment->patient?->name ?? __('admin.unknown') }}</h2><p class="muted-number" dir="ltr">{{ $appointment->patient?->phone ?? '-' }}</p>@if($whatsappPhone !== '')<a href="https://wa.me/{{ $whatsappPhone }}" target="_blank" rel="noopener noreferrer" class="btn btn-outline-success w-100 mt-3"><i class="fab fa-whatsapp me-1"></i>{{ __('admin.open_whatsapp') }}</a>@endif<div class="mt-3"><a href="{{ route('admin.patients.show', $appointment->patient_id) }}" class="btn btn-light w-100"><i class="fas fa-folder-open me-1"></i>{{ __('admin.view_patient_history') }}</a></div></section></div>
</div>
@endsection
