import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../settings/app_settings_cubit.dart';

extension AppTranslate on BuildContext {
  String tr(String key) {
    final languageCode = watch<AppSettingsCubit>().state.locale.languageCode;
    return AppLocalizations.text(key, languageCode);
  }

  String readTr(String key) {
    final languageCode = read<AppSettingsCubit>().state.locale.languageCode;
    return AppLocalizations.text(key, languageCode);
  }
}

class AppLocalizations {
  static String text(String key, String languageCode) {
    final map = _values[languageCode] ?? _values['ar']!;
    return map[key] ?? _values['en']![key] ?? key;
  }

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'app_name': 'Hanova',
      'home': 'Home',
      'clinic': 'Clinic',
      'chat': 'Chat',
      'orders': 'Orders',
      'profile': 'Profile',
      'login': 'Login',
      'register': 'Register',
      'create_account': 'Create Account',
      'logout': 'Logout',
      'cancel': 'Cancel',
      'save': 'Save',
      'try_again': 'Try Again',
      'see_all': 'See All',
      'no_data_available': 'No data available',
      'language': 'Language',
      'display_currency': 'Display currency',
      'currency_syp_old': 'Old Syrian pound',
      'currency_syp_new': 'New Syrian pound',
      'currency_usd': 'US Dollar',
      'currency_rate_note':
          'Conversion rates are managed by the Hanova clinic.',
      'arabic': 'Arabic',
      'english': 'English',
      'notifications': 'Notifications',
      'security': 'Security',
      'help_center': 'Help Center',
      'edit_profile': 'Edit Profile',
      'order_history': 'Order History',
      'guest_user': 'Guest User',
      'login_to_unlock': 'Login to unlock full features',
      'guest_browsing': 'You are browsing as guest.',
      'guest_browsing_note':
          'Create an account to order products and book consultations.',
      'my_profile': 'My Profile',
      'search_products': 'Search skincare products...',
      'skin_consultation': 'Skin Consultation',
      'home_banner_copy':
          'Browse products as guest.\nLogin only when booking or ordering.',
      'book_now': 'Book Now',
      'login_to_book': 'Login to Book',
      'order_now': 'Order Now',
      'shop_banner_title': 'Hanova Care Picks',
      'shop_banner_copy':
          'Choose what suits you from clinic-selected care products.',
      'clinic_banner_copy':
          'Book a clinic or online appointment at a time that is actually available.',
      'categories': 'Categories',
      'all_catalog': 'All',
      'care_products': 'Products',
      'bundles': 'Bundles',
      'care_sessions': 'Sessions',
      'nutrition': 'Nutrition',
      'top_products': 'Top Products',
      'skin_care': 'Skin Care',
      'serums': 'Serums',
      'cleansers': 'Cleansers',
      'sun_protection': 'Sun Protection',
      'added_to_cart': 'Added to cart',
      'view_cart': 'View Cart',
      'stock_available': 'Available: :count',
      'stock_low': 'Low stock: :count left',
      'out_of_stock': 'Out of stock',
      'shopping_cart': 'Shopping Cart',
      'clear': 'Clear',
      'cart_empty': 'Your cart is empty',
      'cart_empty_note': 'Browse products and add your favorites.',
      'start_shopping': 'Start Shopping',
      'guest_checkout_notice':
          'You are browsing as guest. Login is required at checkout.',
      'subtotal': 'Subtotal',
      'delivery_fee': 'Delivery Fee',
      'total': 'Total',
      'proceed_checkout': 'Continue to Order',
      'checkout': 'Complete Order',
      'shipping_address': 'Shipping Address',
      'payment_method': 'Payment Method',
      'cash_on_delivery': 'Cash on Delivery',
      'pay_after_confirm': 'Pay cash when you receive your order.',
      'credit_card': 'Credit Card',
      'apple_pay': 'Apple Pay',
      'gateway_needed': 'Needs a payment gateway before activation.',
      'payment_info':
          'Your order will be confirmed now. Pay cash when you receive it or pick it up; no payment receipt is needed.',
      'order_summary': 'Order Summary',
      'items': 'Items',
      'delivery': 'Delivery',
      'place_order': 'Confirm Order',
      'login_required': 'Login Required',
      'login_required_order': 'Please login first to place your order.',
      'my_orders': 'My Orders',
      'no_orders': 'No orders yet',
      'no_orders_note': 'Your product orders will appear here after checkout.',
      'browse_products': 'Browse Products',
      'total_amount': 'Total Amount',
      'my_clinic': 'My Clinic',
      'clinic_care': 'Clinic Care',
      'clinic_care_note':
          'Book visits, follow appointments, and chat with the clinic team from one place.',
      'appointment': 'Appointment',
      'live_chat': 'Live Chat',
      'bot': 'Bot',
      'upcoming_appointments': 'Upcoming Appointments',
      'medical_followup': 'Medical Follow-up',
      'no_appointments': 'No appointments yet',
      'no_appointments_note': 'Your booked consultations will appear here.',
      'followup_note':
          'Before/after images and doctor notes will appear here when added by the clinic.',
      'clinic_login_note':
          'Please login to view clinic appointments and medical records.',
      'clinic_support': 'Clinic Support',
      'live_chat_subtitle': 'Live chat',
      'open_whatsapp': 'Message patient on WhatsApp',
      'whatsapp_open_failed': 'Could not open WhatsApp.',
      'chat_login_note':
          'Please login to chat with the doctor and clinic staff.',
      'start_chat': 'Start your consultation chat',
      'start_chat_note':
          'Send your first message and our clinic team will reply.',
      'write_message': 'Write your message...',
      'attach_medical_file': 'Attach photo or medical file',
      'medical_attachment': 'Medical attachment',
      'message_failed': 'Message could not be delivered. Please try again.',
      'bot_title': 'Beauty Assistant',
      'bot_subtitle': 'Ask about products, routines, and common skin concerns.',
      'bot_guest_note':
          'The bot works without login. Orders and appointments require an account.',
      'bot_welcome':
          'Welcome to Hanova beauty assistant. What would you like help with today?',
      'book_consultation': 'Book Consultation',
      'book_appointment': 'Book an Appointment',
      'select_session_type': 'Where would you like the appointment?',
      'appointment_type': 'Appointment Type',
      'available_time': 'Available Time',
      'select_date_time': 'Please select a date and time.',
      'confirm_booking': 'Confirm Booking',
      'clinic_session': 'At the Clinic',
      'online_session': 'Online',
      'consultation_type': 'Consultation',
      'treatment_type': 'Treatment',
      'session_type': 'Care Session',
      'duration_15_min': '15 minutes',
      'consultation_subject': 'Consultation subject',
      'skin_consultation_subject': 'Skin',
      'hair_consultation_subject': 'Hair',
      'nutrition_consultation_subject': 'Nutrition (online only)',
      'duration_30_min': '30 minutes',
      'duration_60_min': '60 minutes',
      'no_available_times': 'No available times for this day.',
      'login_required_appointment':
          'Please login first to book your consultation.',
      'pigmentation': 'Pigmentation',
      'acne': 'Acne',
      'hair_issues': 'Hair issues',
      'dark_circles': 'Dark circles',
      'pores': 'Large pores',
      'body_pigmentation': 'Body pigmentation',
      'stretch_marks': 'Stretch marks',
      'cellulite': 'Cellulite',
      'not_sure': 'Not sure',
      'ask_bot_hint': 'Ask the bot...',
      'bot_error': 'Sorry, an error happened. Please try again.',
      'no_answer': 'No answer found.',
      'no_notifications': 'No notifications yet',
      'no_notifications_note':
          'Order updates, ready alerts, and offers will appear here.',
      'notifications_login_note':
          'Login to see order updates, clinic messages, and offers.',
      'order_confirmation': 'Order Confirmation',
      'order_confirmed_title': 'Order Confirmed',
      'order_confirmed_body':
          'Your request has been sent to the clinic.\nWe will contact you shortly for confirmation.',
      'track_order_updates_note':
          'Track your order updates from the Orders screen.',
      'view_my_orders': 'View My Orders',
      'back_to_home': 'Back to Home',
      'product_details': 'Product Details',
      'verified_phone': 'Verified phone',
      'verified_phone_note': 'This phone is linked to your Hanova account.',
      'login_to_manage_security': 'Login to view and manage account security.',
      'secure_session': 'Secure session',
      'secure_session_note':
          'Your sign-in token is stored in protected device storage and sent only over HTTPS.',
      'otp_protection': 'OTP protection',
      'otp_protection_note':
          'Never share your verification code. Hanova staff will not ask for it.',
      'secure_logout': 'Sign out from this device',
      'account_protected': 'Your account is protected',
      'protect_your_account': 'Protect your Hanova account',
      'security_overview_note':
          'Review your active account session and verification status.',
      'how_can_we_help': 'How can we help?',
      'help_intro':
          'Find answers managed by the clinic, or contact the care team directly.',
      'frequent_questions': 'Frequently asked questions',
      'no_faqs': 'No help articles are available yet.',
    },
    'ar': {
      'app_name': 'Hanova',
      'home': 'الرئيسية',
      'clinic': 'العيادة',
      'chat': 'المحادثة',
      'orders': 'الطلبات',
      'profile': 'حسابي',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'create_account': 'إنشاء حساب',
      'logout': 'تسجيل الخروج',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'try_again': 'إعادة المحاولة',
      'see_all': 'عرض الكل',
      'no_data_available': 'لا توجد بيانات متاحة',
      'language': 'اللغة',
      'display_currency': 'عملة العرض',
      'currency_syp_old': 'الليرة السورية القديمة',
      'currency_syp_new': 'الليرة السورية الجديدة',
      'currency_usd': 'الدولار الأمريكي',
      'currency_rate_note':
          'أسعار التحويل تحددها إدارة Hanova وتظهر تلقائياً عند ضبطها.',
      'arabic': 'العربية',
      'english': 'English',
      'notifications': 'الإشعارات',
      'security': 'الأمان',
      'help_center': 'مركز المساعدة',
      'edit_profile': 'تعديل الحساب',
      'order_history': 'سجل الطلبات',
      'guest_user': 'زائر',
      'login_to_unlock': 'سجلي الدخول لتفعيل كل الميزات',
      'guest_browsing': 'أنت تتصفح كزائر.',
      'guest_browsing_note': 'أنشئ حساباً للطلب وحجز الاستشارات.',
      'my_profile': 'حسابي',
      'search_products': 'ابحثي عن منتجات العناية...',
      'skin_consultation': 'استشارة البشرة',
      'home_banner_copy':
          'تصفحي المنتجات كزائرة.\nتسجيل الدخول فقط عند الحجز أو الطلب.',
      'book_now': 'احجزي الآن',
      'login_to_book': 'سجلي للحجز',
      'order_now': 'اطلبي الآن',
      'shop_banner_title': 'مختارات Hanova للعناية',
      'shop_banner_copy':
          'اختاري ما يناسبك من منتجات العناية المختارة من العيادة.',
      'clinic_banner_copy':
          'احجزي موعداً في العيادة أو أونلاين ضمن الأوقات المتاحة فعلياً.',
      'categories': 'التصنيفات',
      'all_catalog': 'الكل',
      'care_products': 'المنتجات',
      'bundles': 'البكجات',
      'care_sessions': 'الجلسات',
      'nutrition': 'التغذية',
      'top_products': 'أفضل المنتجات',
      'skin_care': 'العناية بالبشرة',
      'serums': 'السيرومات',
      'cleansers': 'الغسولات',
      'sun_protection': 'واقي الشمس',
      'added_to_cart': 'تمت الإضافة إلى السلة',
      'view_cart': 'عرض السلة',
      'stock_available': 'متوفر: :count',
      'stock_low': 'المتبقي قليل: :count',
      'out_of_stock': 'نفد المخزون',
      'shopping_cart': 'سلة المشتريات',
      'clear': 'تفريغ',
      'cart_empty': 'السلة فارغة',
      'cart_empty_note': 'تصفحي المنتجات وأضيفي ما يناسبك.',
      'start_shopping': 'ابدئي التسوق',
      'guest_checkout_notice': 'أنت تتصفح كزائر. تسجيل الدخول مطلوب عند الدفع.',
      'subtotal': 'المجموع الفرعي',
      'delivery_fee': 'رسوم التوصيل',
      'total': 'الإجمالي',
      'proceed_checkout': 'متابعة إتمام الطلب',
      'checkout': 'إتمام الطلب',
      'shipping_address': 'عنوان التوصيل',
      'payment_method': 'طريقة الدفع',
      'cash_on_delivery': 'الدفع عند الاستلام',
      'pay_after_confirm': 'الدفع نقداً عند استلام الطلب.',
      'credit_card': 'بطاقة ائتمان',
      'apple_pay': 'Apple Pay',
      'gateway_needed': 'تحتاج بوابة دفع قبل التفعيل.',
      'payment_info':
          'سيتم تأكيد الطلب الآن. الدفع نقداً عند التوصيل أو الاستلام، ولا حاجة لرفع إشعار دفع.',
      'order_summary': 'ملخص الطلب',
      'items': 'المنتجات',
      'delivery': 'التوصيل',
      'place_order': 'تأكيد وإرسال الطلب',
      'login_required': 'تسجيل الدخول مطلوب',
      'login_required_order': 'يرجى تسجيل الدخول أولاً لإرسال الطلب.',
      'my_orders': 'طلباتي',
      'no_orders': 'لا توجد طلبات بعد',
      'no_orders_note': 'طلباتك ستظهر هنا بعد إتمام الشراء.',
      'browse_products': 'تصفح المنتجات',
      'total_amount': 'المبلغ الإجمالي',
      'my_clinic': 'عيادتي',
      'clinic_care': 'متابعة العيادة',
      'clinic_care_note':
          'احجزي المواعيد وتابعي الاستشارات وتواصلي مع فريق العيادة من مكان واحد.',
      'appointment': 'موعد',
      'live_chat': 'محادثة مباشرة',
      'bot': 'البوت',
      'upcoming_appointments': 'المواعيد القادمة',
      'medical_followup': 'المتابعة الطبية',
      'no_appointments': 'لا توجد مواعيد بعد',
      'no_appointments_note': 'المواعيد التي تحجزينها ستظهر هنا.',
      'followup_note':
          'صور قبل/بعد وملاحظات الطبيبة ستظهر هنا عند إضافتها من العيادة.',
      'clinic_login_note':
          'يرجى تسجيل الدخول لعرض مواعيد العيادة والسجل الطبي.',
      'clinic_support': 'دعم العيادة',
      'live_chat_subtitle': 'محادثة مباشرة',
      'open_whatsapp': 'مراسلة المريضة عبر واتساب',
      'whatsapp_open_failed': 'تعذر فتح واتساب.',
      'chat_login_note': 'يرجى تسجيل الدخول للتواصل مع الطبيبة وفريق العيادة.',
      'start_chat': 'ابدئي محادثة الاستشارة',
      'start_chat_note': 'أرسلي رسالتك الأولى وسيقوم فريق العيادة بالرد.',
      'write_message': 'اكتبي رسالتك...',
      'attach_medical_file': 'إرفاق صورة أو تحليل',
      'medical_attachment': 'مرفق طبي',
      'message_failed': 'تعذر إرسال الرسالة. حاولي مرة أخرى.',
      'bot_title': 'مساعد الجمال',
      'bot_subtitle': 'اسألي عن المنتجات والروتين ومشاكل البشرة الشائعة.',
      'bot_guest_note':
          'البوت يعمل بدون تسجيل دخول. الطلبات والمواعيد تحتاج حساباً.',
      'bot_welcome':
          'أهلاً بك في مساعد Hanova للجمال. ما المشكلة التي ترغبين بمعالجتها اليوم؟',
      'book_consultation': 'احجزي استشارة',
      'book_appointment': 'حجز موعد',
      'select_session_type': 'أين تريدين إجراء الموعد؟',
      'appointment_type': 'نوع الموعد',
      'available_time': 'الأوقات المتاحة',
      'select_date_time': 'يرجى اختيار التاريخ والوقت.',
      'confirm_booking': 'تأكيد الحجز',
      'clinic_session': 'في العيادة',
      'online_session': 'أونلاين',
      'consultation_type': 'استشارة',
      'treatment_type': 'علاج',
      'session_type': 'جلسة عناية',
      'duration_15_min': '15 دقيقة',
      'consultation_subject': 'موضوع الاستشارة',
      'skin_consultation_subject': 'البشرة',
      'hair_consultation_subject': 'الشعر',
      'nutrition_consultation_subject': 'تغذية أونلاين فقط',
      'duration_30_min': '30 دقيقة',
      'duration_60_min': '60 دقيقة',
      'no_available_times': 'لا توجد أوقات متاحة في هذا اليوم.',
      'login_required_appointment': 'يرجى تسجيل الدخول أولاً لحجز الاستشارة.',
      'pigmentation': 'التصبغات',
      'acne': 'حب الشباب',
      'hair_issues': 'مشاكل الشعر',
      'dark_circles': 'الهالات السوداء',
      'pores': 'توسع المسامات',
      'body_pigmentation': 'تصبغات الجسم',
      'stretch_marks': 'علامات التمدد',
      'cellulite': 'السيلوليت',
      'not_sure': 'غير متأكدة',
      'ask_bot_hint': 'اسألي البوت...',
      'bot_error': 'حدث خطأ، يرجى المحاولة مرة أخرى.',
      'no_answer': 'لا توجد إجابة مناسبة.',
      'no_notifications': 'لا توجد إشعارات بعد',
      'no_notifications_note': 'تحديثات الطلبات والعروض والتنبيهات ستظهر هنا.',
      'notifications_login_note':
          'سجلي الدخول لمتابعة تحديثات الطلبات ورسائل العيادة والعروض.',
      'order_confirmation': 'تأكيد الطلب',
      'order_confirmed_title': 'تم تأكيد الطلب',
      'order_confirmed_body':
          'تم إرسال طلبك إلى العيادة.\nسنتواصل معك قريباً للتأكيد.',
      'track_order_updates_note': 'تابعي تحديثات طلبك من شاشة الطلبات.',
      'view_my_orders': 'عرض طلباتي',
      'back_to_home': 'الرجوع للرئيسية',
      'product_details': 'تفاصيل المنتج',
      'verified_phone': 'رقم الهاتف الموثق',
      'verified_phone_note': 'هذا الرقم مرتبط بحسابك في Hanova.',
      'login_to_manage_security': 'سجلي الدخول لعرض وإدارة أمان حسابك.',
      'secure_session': 'جلسة آمنة',
      'secure_session_note':
          'يُحفظ رمز الدخول في مساحة الجهاز الآمنة ولا يُرسل إلا عبر اتصال HTTPS.',
      'otp_protection': 'حماية رمز التحقق',
      'otp_protection_note':
          'لا تشاركي رمز التحقق مع أحد. فريق Hanova لن يطلبه منك.',
      'secure_logout': 'تسجيل خروج آمن من هذا الجهاز',
      'account_protected': 'حسابك محمي',
      'protect_your_account': 'احمي حساب Hanova',
      'security_overview_note': 'راجعي جلسة الحساب الحالية وحالة التحقق.',
      'how_can_we_help': 'كيف يمكننا مساعدتك؟',
      'help_intro':
          'اطلعي على إجابات العيادة أو تواصلي مباشرة مع فريق العناية.',
      'frequent_questions': 'الأسئلة الشائعة',
      'no_faqs': 'لا توجد مقالات مساعدة متاحة حالياً.',
    },
  };
}
