import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../settings/app_settings_cubit.dart';

extension AppTranslate on BuildContext {
  String tr(String key) {
    final languageCode = watch<AppSettingsCubit>().state.locale.languageCode;
    return AppLocalizations.text(key, languageCode);
  }

  String readTr(String key) {
    final languageCode = read<AppSettingsCubit>().state.locale.languageCode;
    return AppLocalizations.text(key, languageCode);
  }
}

class AppLocalizations {
  static String text(String key, String languageCode) {
    final map = _values[languageCode] ?? _values['ar']!;
    return map[key] ?? _values['en']![key] ?? key;
  }

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'app_name': 'Hanova',
      'home': 'Home',
      'clinic': 'Clinic',
      'chat': 'Chat',
      'orders': 'Orders',
      'profile': 'Profile',
      'login': 'Login',
      'register': 'Register',
      'create_account': 'Create Account',
      'logout': 'Logout',
      'cancel': 'Cancel',
      'save': 'Save',
      'try_again': 'Try Again',
      'see_all': 'See All',
      'no_data_available': 'No data available',
      'language': 'Language',
      'arabic': 'Arabic',
      'english': 'English',
      'notifications': 'Notifications',
      'security': 'Security',
      'help_center': 'Help Center',
      'edit_profile': 'Edit Profile',
      'order_history': 'Order History',
      'guest_user': 'Guest User',
      'login_to_unlock': 'Login to unlock full features',
      'guest_browsing': 'You are browsing as guest.',
      'guest_browsing_note':
          'Create an account to order products and book consultations.',
      'my_profile': 'My Profile',
      'search_products': 'Search skincare products...',
      'skin_consultation': 'Skin Consultation',
      'home_banner_copy':
          'Browse products as guest.\nLogin only when booking or ordering.',
      'book_now': 'Book Now',
      'login_to_book': 'Login to Book',
      'categories': 'Categories',
      'top_products': 'Top Products',
      'skin_care': 'Skin Care',
      'serums': 'Serums',
      'cleansers': 'Cleansers',
      'sun_protection': 'Sun Protection',
      'added_to_cart': 'Added to cart',
      'view_cart': 'View Cart',
      'shopping_cart': 'Shopping Cart',
      'clear': 'Clear',
      'cart_empty': 'Your cart is empty',
      'cart_empty_note': 'Browse products and add your favorites.',
      'start_shopping': 'Start Shopping',
      'guest_checkout_notice':
          'You are browsing as guest. Login is required at checkout.',
      'subtotal': 'Subtotal',
      'delivery_fee': 'Delivery Fee',
      'total': 'Total',
      'proceed_checkout': 'Proceed to Checkout',
      'checkout': 'Checkout',
      'shipping_address': 'Shipping Address',
      'payment_method': 'Payment Method',
      'cash_on_delivery': 'Cash on Delivery',
      'pay_after_confirm': 'Pay after the clinic confirms your order.',
      'credit_card': 'Credit Card',
      'apple_pay': 'Apple Pay',
      'gateway_needed': 'Needs a payment gateway before activation.',
      'payment_info':
          'Online payment is not connected yet. This order will be saved in Laravel for clinic confirmation.',
      'order_summary': 'Order Summary',
      'items': 'Items',
      'delivery': 'Delivery',
      'place_order': 'Place Order',
      'login_required': 'Login Required',
      'login_required_order': 'Please login first to place your order.',
      'my_orders': 'My Orders',
      'no_orders': 'No orders yet',
      'no_orders_note': 'Your product orders will appear here after checkout.',
      'browse_products': 'Browse Products',
      'total_amount': 'Total Amount',
      'my_clinic': 'My Clinic',
      'clinic_care': 'Clinic Care',
      'clinic_care_note':
          'Book visits, follow appointments, and chat with the clinic team from one place.',
      'appointment': 'Appointment',
      'live_chat': 'Live Chat',
      'bot': 'Bot',
      'upcoming_appointments': 'Upcoming Appointments',
      'medical_followup': 'Medical Follow-up',
      'no_appointments': 'No appointments yet',
      'no_appointments_note': 'Your booked consultations will appear here.',
      'followup_note':
          'Before/after images and doctor notes will appear here when added by the clinic.',
      'clinic_login_note':
          'Please login to view clinic appointments and medical records.',
      'clinic_support': 'Clinic Support',
      'live_chat_subtitle': 'Live chat',
      'chat_login_note':
          'Please login to chat with the doctor and clinic staff.',
      'start_chat': 'Start your consultation chat',
      'start_chat_note':
          'Send your first message and our clinic team will reply.',
      'write_message': 'Write your message...',
      'message_failed': 'Message could not be delivered. Please try again.',
      'bot_title': 'Beauty Assistant',
      'bot_subtitle': 'Ask about products, routines, and common skin concerns.',
      'bot_guest_note':
          'The bot works without login. Orders and appointments require an account.',
      'bot_welcome':
          'Welcome to Hanova beauty assistant. What would you like help with today?',
      'book_consultation': 'Book Consultation',
      'pigmentation': 'Pigmentation',
      'acne': 'Acne',
      'hair_issues': 'Hair issues',
      'dark_circles': 'Dark circles',
      'pores': 'Large pores',
      'body_pigmentation': 'Body pigmentation',
      'stretch_marks': 'Stretch marks',
      'cellulite': 'Cellulite',
      'not_sure': 'Not sure',
      'ask_bot_hint': 'Ask the bot...',
      'bot_error': 'Sorry, an error happened. Please try again.',
      'no_answer': 'No answer found.',
      'no_notifications': 'No notifications yet',
      'no_notifications_note':
          'Order updates, ready alerts, and offers will appear here.',
      'notifications_login_note':
          'Login to see order updates, clinic messages, and offers.',
      'order_confirmation': 'Order Confirmation',
      'order_confirmed_title': 'Order Confirmed',
      'order_confirmed_body':
          'Your request has been sent to the clinic.\nWe will contact you shortly for confirmation.',
      'track_order_updates_note':
          'Track your order updates from the Orders screen.',
      'view_my_orders': 'View My Orders',
      'back_to_home': 'Back to Home',
      'product_details': 'Product Details',
    },
    'ar': {
      'app_name': 'Hanova',
      'home': 'الرئيسية',
      'clinic': 'العيادة',
      'chat': 'المحادثة',
      'orders': 'الطلبات',
      'profile': 'حسابي',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'create_account': 'إنشاء حساب',
      'logout': 'تسجيل الخروج',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'try_again': 'إعادة المحاولة',
      'see_all': 'عرض الكل',
      'no_data_available': 'لا توجد بيانات متاحة',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'notifications': 'الإشعارات',
      'security': 'الأمان',
      'help_center': 'مركز المساعدة',
      'edit_profile': 'تعديل الحساب',
      'order_history': 'سجل الطلبات',
      'guest_user': 'زائر',
      'login_to_unlock': 'سجلي الدخول لتفعيل كل الميزات',
      'guest_browsing': 'أنت تتصفح كزائر.',
      'guest_browsing_note': 'أنشئ حساباً للطلب وحجز الاستشارات.',
      'my_profile': 'حسابي',
      'search_products': 'ابحثي عن منتجات العناية...',
      'skin_consultation': 'استشارة البشرة',
      'home_banner_copy':
          'تصفحي المنتجات كزائرة.\nتسجيل الدخول فقط عند الحجز أو الطلب.',
      'book_now': 'احجزي الآن',
      'login_to_book': 'سجلي للحجز',
      'categories': 'التصنيفات',
      'top_products': 'أفضل المنتجات',
      'skin_care': 'العناية بالبشرة',
      'serums': 'السيرومات',
      'cleansers': 'الغسولات',
      'sun_protection': 'واقي الشمس',
      'added_to_cart': 'تمت الإضافة إلى السلة',
      'view_cart': 'عرض السلة',
      'shopping_cart': 'سلة المشتريات',
      'clear': 'تفريغ',
      'cart_empty': 'السلة فارغة',
      'cart_empty_note': 'تصفحي المنتجات وأضيفي ما يناسبك.',
      'start_shopping': 'ابدئي التسوق',
      'guest_checkout_notice': 'أنت تتصفح كزائر. تسجيل الدخول مطلوب عند الدفع.',
      'subtotal': 'المجموع الفرعي',
      'delivery_fee': 'رسوم التوصيل',
      'total': 'الإجمالي',
      'proceed_checkout': 'المتابعة للدفع',
      'checkout': 'إتمام الطلب',
      'shipping_address': 'عنوان التوصيل',
      'payment_method': 'طريقة الدفع',
      'cash_on_delivery': 'الدفع عند الاستلام',
      'pay_after_confirm': 'الدفع بعد تأكيد الطلب من العيادة.',
      'credit_card': 'بطاقة ائتمان',
      'apple_pay': 'Apple Pay',
      'gateway_needed': 'تحتاج بوابة دفع قبل التفعيل.',
      'payment_info':
          'الدفع الإلكتروني غير مربوط حالياً. سيتم حفظ الطلب في Laravel لتأكيده من العيادة.',
      'order_summary': 'ملخص الطلب',
      'items': 'المنتجات',
      'delivery': 'التوصيل',
      'place_order': 'تأكيد الطلب',
      'login_required': 'تسجيل الدخول مطلوب',
      'login_required_order': 'يرجى تسجيل الدخول أولاً لإرسال الطلب.',
      'my_orders': 'طلباتي',
      'no_orders': 'لا توجد طلبات بعد',
      'no_orders_note': 'طلباتك ستظهر هنا بعد إتمام الشراء.',
      'browse_products': 'تصفح المنتجات',
      'total_amount': 'المبلغ الإجمالي',
      'my_clinic': 'عيادتي',
      'clinic_care': 'متابعة العيادة',
      'clinic_care_note':
          'احجزي المواعيد وتابعي الاستشارات وتواصلي مع فريق العيادة من مكان واحد.',
      'appointment': 'موعد',
      'live_chat': 'محادثة مباشرة',
      'bot': 'البوت',
      'upcoming_appointments': 'المواعيد القادمة',
      'medical_followup': 'المتابعة الطبية',
      'no_appointments': 'لا توجد مواعيد بعد',
      'no_appointments_note': 'المواعيد التي تحجزينها ستظهر هنا.',
      'followup_note':
          'صور قبل/بعد وملاحظات الطبيبة ستظهر هنا عند إضافتها من العيادة.',
      'clinic_login_note':
          'يرجى تسجيل الدخول لعرض مواعيد العيادة والسجل الطبي.',
      'clinic_support': 'دعم العيادة',
      'live_chat_subtitle': 'محادثة مباشرة',
      'chat_login_note': 'يرجى تسجيل الدخول للتواصل مع الطبيبة وفريق العيادة.',
      'start_chat': 'ابدئي محادثة الاستشارة',
      'start_chat_note': 'أرسلي رسالتك الأولى وسيقوم فريق العيادة بالرد.',
      'write_message': 'اكتبي رسالتك...',
      'message_failed': 'تعذر إرسال الرسالة. حاولي مرة أخرى.',
      'bot_title': 'مساعد الجمال',
      'bot_subtitle': 'اسألي عن المنتجات والروتين ومشاكل البشرة الشائعة.',
      'bot_guest_note':
          'البوت يعمل بدون تسجيل دخول. الطلبات والمواعيد تحتاج حساباً.',
      'bot_welcome':
          'أهلاً بك في مساعد Hanova للجمال. ما المشكلة التي ترغبين بمعالجتها اليوم؟',
      'book_consultation': 'احجزي استشارة',
      'pigmentation': 'التصبغات',
      'acne': 'حب الشباب',
      'hair_issues': 'مشاكل الشعر',
      'dark_circles': 'الهالات السوداء',
      'pores': 'توسع المسامات',
      'body_pigmentation': 'تصبغات الجسم',
      'stretch_marks': 'علامات التمدد',
      'cellulite': 'السيلوليت',
      'not_sure': 'غير متأكدة',
      'ask_bot_hint': 'اسألي البوت...',
      'bot_error': 'حدث خطأ، يرجى المحاولة مرة أخرى.',
      'no_answer': 'لا توجد إجابة مناسبة.',
      'no_notifications': 'لا توجد إشعارات بعد',
      'no_notifications_note': 'تحديثات الطلبات والعروض والتنبيهات ستظهر هنا.',
      'notifications_login_note':
          'سجلي الدخول لمتابعة تحديثات الطلبات ورسائل العيادة والعروض.',
      'order_confirmation': 'تأكيد الطلب',
      'order_confirmed_title': 'تم تأكيد الطلب',
      'order_confirmed_body':
          'تم إرسال طلبك إلى العيادة.\nسنتواصل معك قريباً للتأكيد.',
      'track_order_updates_note': 'تابعي تحديثات طلبك من شاشة الطلبات.',
      'view_my_orders': 'عرض طلباتي',
      'back_to_home': 'الرجوع للرئيسية',
      'product_details': 'تفاصيل المنتج',
    },
  };
}
